### ISSUE TITLE
Unable to Deploy it to Vercel or Netlify

### ISSUE THREAD

**Issue by navsing** [nuxt-themes/alpine#114]
I am trying to deploy it to Vercel or Netlify but I get

`Failed during stage 'building site': Deploy directory 'dist' does not exist`

I tried updating the directory from dist to .code based on my package.json -> it builds successfully but I get a 404 error when I try to access the website

Here is what the package.json looks like (I didn't change anything after cloning):

```
"scripts": {
    "prepare": "nuxi prepare && nuxi prepare .docs",
    "build": "nuxt build .docs",
    "dev": "nuxt dev .docs",
    "lint": "eslint .",
    "generate": "nuxt generate .docs",
    "preview": "nuxt preview .docs",
    "prepublishOnly": "pnpm lint",
    "release": "release-it"
  },
```

I would appreciate any pointers on the best way to deploy this. Thanks!

**Comment by Atinux** [comment]
Actually you should not use this project to get started but the starter on https://github.com/nuxt-themes/alpine

Did you use the `npx nuxi@latest init -t themes/alpine` command?

**Comment by navsing** [comment]
Yes, just running that command, pushing it to Github, and then deploying on vercel/netlify, fails.

It builds locally, and also works perfect in development on local

**Comment by Atinux** [comment]
Do you have a reproduction?
