### ISSUE TITLE
Doesn't work on clone

### ISSUE THREAD

**Issue by ennioVisco** [nuxt-themes/alpine#119]
It doesn't work on clone, nor on vercel setup

**Comment by ennioVisco** [comment]
> It works on my end. What are you trying to clone?
> 
> Did you run `npx nuxi@latest init -t themes/alpine` ?

I can confirm it works cloning the branch, I don't know what I was doing wrong before. 
The problem still persists on the vercel template I assume: https://vercel.com/templates/nuxt/alpine

**Comment by Atinux** [comment]
Thank you @ennioVisco 

I contacted the Vercel team to link to the correct starter instead.
