### ISSUE TITLE
[Bug] Article title height show wrong

### ISSUE THREAD

**Issue by gumingWu** [nuxt-themes/alpine#125]
![image](https://user-images.githubusercontent.com/24989299/231761526-4321ee1f-3763-41ce-b330-1801c8824978.png)

when I use `y`, it show wrong

**Comment by Atinux** [comment]
Happy to open a PR @gumingWu ?

**Comment by gumingWu** [comment]
> Happy to open a PR @gumingWu ?

Sorry about that. I want to fix it, but after `pnpm install` and `pnpm dev`, it show errors

 
![image](https://user-images.githubusercontent.com/24989299/233544464-fc2ec2c9-16c0-42a4-a54c-38a20ba39c50.png)

and I run dev twice, the server failed

![image](https://user-images.githubusercontent.com/24989299/233544700-9bf03ca7-4bfc-460f-a679-83bf04dea0bd.png)
