### ISSUE TITLE
How to add favicon.ico？

### ISSUE THREAD

**Issue by yyrc** [nuxt-themes/alpine#140]
How to add favicon.ico for my blog？

**Comment by Atinux** [comment]
You can add your `favicon.ico` in the `public/` directory

**Comment by fanckush** [comment]
@Atinux how do add it to the header? is there a config to define head meta tags?

**Comment by Atinux** [comment]
It's actually the browser that will try to get it from the header automatically.

You can use the `alpine.head` property in your `app.config.ts` @fanckush

**Comment by riddla** [comment]
@Atinux, how and where is this implemented?

I'm currently researching best practices around Nuxt and SEO and can't find the `alpine.head` (for example within https://github.com/nuxt-themes/alpine/blob/46c2412569a1e0c439b4932590e47f316a5069cf/nuxt.schema.ts).

**Comment by Atinux** [comment]
It's used in https://github.com/nuxt-themes/alpine/blob/46c2412569a1e0c439b4932590e47f316a5069cf/components/AppLayout.vue#L17
