### ISSUE TITLE
Canonical and og:url are not set 

### ISSUE THREAD

**Issue by galaxy79** [nuxt-themes/alpine#157]
I was trying to test the alpine theme and saw that canonical and og:url properties are missing in the generated html file.

<img width="957" alt="image" src="https://github.com/nuxt-themes/alpine/assets/18106251/fe0f40fd-d89f-42f8-9d8d-608d11ccf4f0">

**Comment by Atinux** [comment]
You can define them in your `nuxt.config.ts` @galaxy79 for `og:url` and `og:type` using https://nuxt.com/docs/api/configuration/nuxt-config#head

I guess for the canonical we could add it in our `AppLayout` @bdrtsky

**Comment by galaxy79** [comment]
Thanks .. I did it.. since it was released as a theme and these are important parameters for SEO, I thought it is better to be raise the issue

**Comment by galaxy79** [comment]
@Atinux i defined it in `nuxt.config.ts` and it works for the index page. For each blog page, it still has the canonical as by index page url and how can i dynamically update it for each page ?

**Comment by deepinder10** [comment]
@Atinux I ran into the same issue as @galaxy79 . I have raised a PR to address it.
https://github.com/nuxt-themes/alpine/pull/194
