### ISSUE TITLE
Microsoft Clarity or Google Analytics

### ISSUE THREAD

**Issue by Kokolinio** [nuxt-themes/alpine#179]
Hi,

I've set up a blog using Alpine template and deployed it on Vercel. It is working fine, however i would like to connect it to Microsoft Clarity or Google Analytics, but after installing a package ("nuxt-gtag" or "nuxt-microsoft-clarity") in the project it would not build.
How can I install one of these analytics tools on Alpine blog?

**Comment by Atinux** [comment]
Hi @Kokolinio 

You can add install the module and add it to your `nuxt.config.ts

**Comment by Kokolinio** [comment]
Hi,
Thanks for replying!
I installed modules and added them to nuxt.config file, but Vercel is unable to build and deploy with them installed. I've noticed that even locally, when I clone and build fresh alpine theme it's ok, but when I install packages it breaks and it won't build. I use yarn as a package manager.
