### ISSUE TITLE
Instagram Social wont dissapear

### ISSUE THREAD

**Issue by ZainW** [nuxt-themes/alpine#93]
very odd issue in regards to the presence and how defaults are handled

if you go to my [site](https://zainwania.dev/) (WIP) you can see that in the social buttons area still includes atinux's instagram even though on the [config](https://github.com/ZainW/zainwaniadev/blob/main/app.config.ts) i removed it 

it seems that there are defaults being loaded from the schema potentially as overrides do work ie adding my own instagram handle

**Comment by Atinux** [comment]
Can you upgrade to [v1.0.2](https://github.com/nuxt-themes/alpine/releases/tag/v1.0.2) @ZainW ?

Thank you for reporting this bug!
